"""
Genuine icosian Brandt build, step 1: the GENUS / Brandt dimension at level p31=(5phi-2).

Method (Dembele): the right-ideal classes of the level-p Eichler order are in bijection with
the orbits of the maximal-order unit group U (= the 120 icosians) acting on P^1(O_K/p) via
the local splitting B (x) O_K/p ~ M_2(F_31). The number of orbits = the Brandt-module
dimension h. ACCEPTANCE GATE: h must be 2 (1 Eisenstein + 1 cuspidal), since the unique
norm-31 Hilbert newform = elliptic curve 31.1-a1 (cuspidal dim 1).

NO fitting: everything is the icosians' own arithmetic reduced mod p31.
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "route_b"))
from fractions import Fraction
import icosian as I

P = 31
PHI_MOD = 19          # phi mod p31: 5*phi-2==0 => phi==2/5; root of x^2-x-1 mod 31 is 19 (and 13)
assert (PHI_MOD*PHI_MOD - PHI_MOD - 1) % P == 0, "phi mod p31 must satisfy x^2-x-1"
assert (5*PHI_MOD - 2) % P == 0, "phi must kill the level generator 5phi-2"
inv2 = pow(2, P-2, P)

def red(frac_pair):
    """reduce a Z[phi] coord (a + b*phi), a,b Fractions, to F_31."""
    a, b = frac_pair
    def rf(fr):
        return (fr.numerator % P) * pow(fr.denominator % P, P-2, P) % P
    return (rf(a) + rf(b)*PHI_MOD) % P

# splitting B=(-1,-1)/F31 -> M_2(F_31):  i^2=j^2=-I, ij=-ji
I_MAT=((1,0),(0,1)); i_MAT=((0,1),(P-1,0)); j_MAT=((5,6),(6,26)); k_MAT=((6,26),(26,25))
def matadd(A,B,C,Dm): return tuple(tuple((A[r][c]+B[r][c]+C[r][c]+Dm[r][c])%P for c in range(2)) for r in range(2))
def scal(s,M): return tuple(tuple((s*M[r][c])%P for c in range(2)) for r in range(2))
def quat_to_mat(q):
    w,x,y,z = (red(c) for c in q)
    return matadd(scal(w,I_MAT), scal(x,i_MAT), scal(y,j_MAT), scal(z,k_MAT))
def det(M): return (M[0][0]*M[1][1]-M[0][1]*M[1][0])%P

# build the 120 units -> PGL_2(F_31) (drop any that reduce to non-invertible)
units = I.unit_icosians()
mats=[]
for q in units:
    M=quat_to_mat(q)
    if det(M)!=0: mats.append(M)
print(f"icosian units: {len(units)};  invertible mod p31: {len(mats)}")

# action on P^1(F_31): points [x:1] (x in F31) and [1:0]
pts=[(x,1) for x in range(P)]+[(1,0)]
def act(M,pt):
    x,y=pt; nx=(M[0][0]*x+M[0][1]*y)%P; ny=(M[1][0]*x+M[1][1]*y)%P
    if ny!=0: return ((nx*pow(ny,P-2,P))%P,1)
    return (1,0) if nx!=0 else None
# orbits under the group generated by the unit matrices
idx={p:k for k,p in enumerate(pts)}
parent=list(range(len(pts)))
def find(a):
    while parent[a]!=a: parent[a]=parent[parent[a]]; a=parent[a]
    return a
def union(a,b):
    ra,rb=find(a),find(b)
    if ra!=rb: parent[ra]=rb
for M in mats:
    for p in pts:
        q=act(M,p)
        if q is not None and q in idx: union(idx[p],idx[q])
orbits={}
for k in range(len(pts)): orbits.setdefault(find(k),[]).append(k)
h=len(orbits)
sizes=sorted(len(v) for v in orbits.values())
print(f"P^1(F_31): {len(pts)} points")
print(f"U-orbits (= Brandt-module dimension h): {h}   orbit sizes: {sizes}")
print(f"\nACCEPTANCE GATE h==2 (1 Eisenstein + 1 cuspidal): {'PASS' if h==2 else 'FAIL ('+str(h)+')'}")
if h==2:
    print("=> the icosian geometry yields Brandt dimension 2 at level (5phi-2), WITHOUT fitting:")
    print("   1 Eisenstein + 1 cuspidal. This is the genus the norm-31 newform lives in.")
else:
    print("=> dimension != 2: either the splitting/reduction needs correction, or the unit")
    print("   action differs. Honest: gate not met; do not proceed to Hecke until h==2.")
