"""Route B, step 6: apply the admissibility classes + explicit formula to
the GENUINE substrate eigenform, and ask honestly whether RH follows.

We now have a real, verified cuspidal eigenform (the icosian Brandt action
at level (5phi-2), eigenvalues = genuine norm-31 newform).  This script:

  (A1) SM  multiplicativity: compute prime-POWER eigenvalues a_{q^2} from
       the substrate and check the Hecke recursion a_{q^2}=a_q^2 - N(q).
  (A6) CB  Ramanujan: |a_q| <= 2 sqrt(N(q))  (here = Hasse bound).
  (A7) ST  Sato-Tate: distribution of a_q/(2 sqrt N(q)).

and then states, honestly, what the Weil explicit formula does and does
NOT give -- the load-bearing question for the Fractal Tiling Theorem.
"""
from __future__ import annotations

import math
from collections import defaultdict
from fractions import Fraction

import icosian as ico
import short_vectors as sv
import step2_eichler as st2


def build_orbits():
    units = ico.unit_icosians()
    mats = [st2.quat_to_matrix(q) for q in units]
    pts = st2.p1_points()
    idx = {pt: n for n, pt in enumerate(pts)}
    parent = list(range(len(pts)))
    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]; a = parent[a]
        return a
    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb: parent[ra] = rb
    for Mt in mats:
        for pt in pts:
            union(idx[pt], idx[st2.act(Mt, pt)])
    orbit_id = {i: find(i) for i in range(len(pts))}
    roots = sorted(set(orbit_id.values()),
                   key=lambda r: -sum(1 for i in orbit_id if orbit_id[i] == r))
    oindex = {r: k for k, r in enumerate(roots)}
    reps = []
    for r in roots:
        reps.append(next(pts[i] for i in range(len(pts)) if orbit_id[i] == r))
    return pts, idx, orbit_id, oindex, reps


def hecke_eigenvalue(nu, deg, xs, pts, idx, orbit_id, oindex, reps):
    """Cuspidal eigenvalue a at the ideal generated by nu (degree = the
    Eisenstein eigenvalue = #norm-nu elements / 120)."""
    Tm = [[0, 0], [0, 0]]
    for k in range(2):
        Li = reps[k]
        for x in xs:
            Mx = st2.quat_to_matrix(x)
            dest = st2.act(Mx, Li)
            j = oindex[orbit_id[idx[dest]]]
            Tm[k][j] += 1
    Tm = [[v // 120 for v in row] for row in Tm]
    rowsum = [sum(r) for r in Tm]
    trace = Tm[0][0] + Tm[1][1]
    a = trace - deg                # deg = Eisenstein eigenvalue (row sum)
    return a, rowsum, Tm


def main():
    print("=" * 74)
    print("ROUTE B step 6: admissibility classes + explicit formula")
    print("on the genuine substrate eigenform")
    print("=" * 74)

    M = 10
    basis, GL, GLf = sv.build_lattice()
    vecs = sv.enumerate_short(GL, GLf, M)
    by_nu = defaultdict(list)
    from step3_4_hecke import reconstruct_quaternion
    for c in vecs:
        nu = sv.reduced_norm_of_combo(c, basis)
        by_nu[(nu[0], nu[1])].append(reconstruct_quaternion(c, basis))
    pts, idx, orbit_id, oindex, reps = build_orbits()

    F = Fraction
    # primes and their squares reachable within M=10
    # q=(2): nu=2 (N=4), q^2=(4): nu=4 (N=16, Tr=8)
    # q=(sqrt5): nu=2+phi (N=5), q^2=(5): nu=5 (N=25, Tr=10)
    cases = [
        ("(2)",   (F(2), F(0)),  4),
        ("(2)^2", (F(4), F(0)),  16),
        ("(rt5)", (F(2), F(1)),  5),
        ("(rt5)^2", (F(5), F(0)), 25),
    ]
    a = {}
    print("\n[A1] Multiplicativity: compute prime + prime-power eigenvalues")
    print("  ideal      N        deg(Eis)  a_value  Ramanujan |a|<=2sqrtN")
    print("  " + "-" * 60)
    for label, nu, Nn in cases:
        xs = by_nu.get(nu, [])
        deg = len(xs) // 120
        av, rowsum, Tm = hecke_eigenvalue(nu, deg, xs, pts, idx,
                                          orbit_id, oindex, reps)
        a[label] = av
        ram = abs(av) <= 2 * math.sqrt(Nn) + 1e-9
        print(f"  {label:<10} {Nn:<8} {deg:<9} {av:<8} "
              f"{'ok' if ram else 'VIOLATION'}")

    print("\n  Hecke recursion check a_{q^2} == a_q^2 - N(q):")
    chk2 = (a["(2)^2"] == a["(2)"] ** 2 - 4)
    chk5 = (a["(rt5)^2"] == a["(rt5)"] ** 2 - 5)
    print(f"    q=(2):    a_4  = {a['(2)^2']},  a_2^2 - 4 = "
          f"{a['(2)']**2 - 4}   {'PASS' if chk2 else 'FAIL'}")
    print(f"    q=(rt5):  a_25 = {a['(rt5)^2']},  a_rt5^2 - 5 = "
          f"{a['(rt5)']**2 - 5}   {'PASS' if chk5 else 'FAIL'}")
    a1 = chk2 and chk5
    print(f"  (A1) MULTIPLICATIVITY: {'PASS' if a1 else 'FAIL'}")

    # (A7) Sato-Tate on the eigenvalues we have (from the circle test)
    print("\n[A7] Sato-Tate: normalised eigenvalues a_q/(2 sqrt N(q))")
    data = [(4, -3), (5, -2), (9, 2), (11, -4), (11, 4), (19, 4),
            (19, -4), (29, -2), (29, -2), (41, -6), (41, -6)]
    xs_st = [aq / (2 * math.sqrt(N)) for N, aq in data]
    print(f"    {len(xs_st)} values in [-1,1]; all |x|<1: "
          f"{all(abs(x) < 1 for x in xs_st)} (Ramanujan strict -> cuspidal)")
    print(f"    (n={len(xs_st)} is too small for a distribution test; "
          f"consistent with semicircle, not a proof)")

    # ----------------------------------------------------------------
    print("\n" + "=" * 74)
    print("EXPLICIT FORMULA + RH: the honest analysis")
    print("=" * 74)
    print("""
The substrate eigenform now PASSES the admissibility classes for real
(not hardcoded): multiplicativity (A1) verified above; Ramanujan (A6)
holds and is in fact the Hasse bound for the elliptic curve 31.1-a over
Q(sqrt5); Sato-Tate (A7) is a THEOREM for this non-CM curve and our data
is consistent; the functional equation (A2) and analytic continuation are
THEOREMS (modularity / Hilbert modular). So L(f,s) is a bona fide degree-4
automorphic L-function (conductor 5^2 * 31 = 775).

The Weil explicit formula is then a VALID IDENTITY relating its zeros to
the prime sum of a_q.  BUT -- and this is the load-bearing honest point --

  a genuine automorphic L-function with a valid explicit formula does
  NOT imply its zeros lie on the critical line.

That statement IS the Riemann Hypothesis for L(f,s) -- equivalently GRH
for the elliptic curve E/Q(sqrt5) -- and it is OPEN.  The explicit formula
is a tool equivalent to information about the zeros; it does not force
them onto the line.  Ramanujan (A6) bounds the prime side; Sato-Tate (A7)
describes the a_q distribution; NEITHER pins the zeros to Re(s)=1.

CONSEQUENCE FOR THE FRACTAL TILING THEOREM (Thm 5.1):
  The step-(3) argument -- 'Sato-Tate forces the residual term to have no
  positive imaginary contribution, hence every gamma_n is real' -- is NOT
  valid.  Passing (A1)-(A7) yields a genuine L-function, not RH.  The
  theorem's hypothesis is now genuinely satisfied at level (5phi-2), but
  its CONCLUSION (RH) does not follow from admissibility + explicit
  formula.  This must be corrected in the paper: (A1)-(A7) certify
  automorphy, and RH for the resulting L-function remains exactly as open
  as GRH.

WHAT IS REAL: the substrate genuinely produces a cuspidal automorphic
eigenform and its (provable) Ramanujan/Sato-Tate/functional-equation
structure.  WHAT IS NOT: a substrate-side proof that its L-zeros are on
the line.  The honest status of the programme is consilience + a verified
arithmetic identification, NOT a proof of RH.
""")


if __name__ == "__main__":
    main()
