"""Phase 1 acceptance: the brute-force point-count target.

>= 44 good prime ideals, all Ramanujan-bounded (hence genuinely cuspidal), all
with 8 | #E(F_P) (the curve's rational 8-torsion), and a few independently
known small a_P values.  The target is generated by point counting only -- no
LMFDB eigenvalue table.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "route_b"))
import point_count_target as pct


def test_count_and_ramanujan():
    rows = pct.compute_target(200)
    assert len(rows) >= 44
    assert all(r["satisfies_ramanujan"] for r in rows)
    assert all(r["torsion_8_divides"] for r in rows)


def test_known_small_values():
    rows = {(_r["norm"], _r["phi_mod_p"]): _r["a_p"]
            for _r in pct.compute_target(60)}
    # a few exact values (point-counted, not from LMFDB)
    by_norm = {}
    for (norm, root), a in rows.items():
        by_norm.setdefault(norm, set()).add(a)
    assert by_norm[4] == {-3}        # inert prime above 2
    assert by_norm[9] == {2}         # inert prime above 3
    assert by_norm[5] == {-2}        # ramified prime
    assert by_norm[11] == {-4, 4}    # the two split primes above 11
    assert by_norm[49] == {2}        # inert prime above 7


def test_source_is_point_count():
    payload, path = pct.write_target()
    assert payload["source"] == "brute_force_point_count"
    assert "lmfdb" not in payload["note"].lower() or "not" in \
        payload["note"].lower()
    os.path.exists(path)


def run():
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            fn()
            print("  ok:", name)
    print("ALL POINT_COUNT_TARGET TESTS PASS")


if __name__ == "__main__":
    run()
