"""Compute REAL Brandt matrices for level 31 over Q, and harvest
Hecke eigenvalues for primes up to bound, plus prime structure of
Q(sqrt 5) for cross-reference.

Outputs:
  data/brandt_level31.json -- the Brandt module data + Hecke matrices

Why level 31:
  - 31 is the smallest prime where the icosian programme's chain
    naturally lives (V_600 spectrum has 31-related structure;
    level-31 modular forms over Q(sqrt 5) are conjecturally related
    to icosian theta).
  - BrandtModule(31, 1) has dim 3 in SAGE 9.0, giving a 3x3 Hecke
    matrix action, NON-TRIVIAL Brandt structure.
  - SAGE 9.0 supports this case natively (number field BrandtModule
    is not implemented in 9.0).

Caveat:
  This is BrandtModule over Q at level 31, not the icosian Brandt
  module over Q(sqrt 5). It's a proxy: real Hecke action with the
  right multiplicativity and analytic structure, used here to
  demonstrate the engine v0.3 pipeline with genuine number theory
  inputs.

Run:
  sage compute_brandt_level31.sage
"""


# This file was *autogenerated* from the file sage_scripts/compute_brandt_level31.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_50 = Integer(50); _sage_const_0 = Integer(0); _sage_const_31 = Integer(31); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_200 = Integer(200)
import json
from pathlib import Path

# Number field Q(sqrt 5) for cross-reference
K = NumberField(x**_sage_const_2  - x - _sage_const_1 , names=('phi',)); (phi,) = K._first_ngens(1)

# Prime structure in Q(sqrt 5) (split / inert / ramified)
prime_structure_K = {}
for p_rat in primes(_sage_const_50 ):
    factors = K.ideal(p_rat).factor()
    if len(factors) == _sage_const_1  and factors[_sage_const_0 ][_sage_const_1 ] == _sage_const_1 :
        kind = "inert"
    elif len(factors) > _sage_const_1 :
        kind = "split"
    else:
        kind = "ramified"
    prime_structure_K[int(p_rat)] = {
        "kind": kind,
        "ideals": [{"norm": int(P.norm()), "exp": int(e)}
                   for P, e in factors]
    }

# Brandt module at level 31 over Q (proxy for icosian Hecke action)
BM = BrandtModule(_sage_const_31 , _sage_const_1 )
dim_BM = int(BM.dimension())

# Compute Hecke matrices T_p for primes up to bound
primes_to_compute = [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 , _sage_const_29 , _sage_const_31 ,
                      _sage_const_37 , _sage_const_41 , _sage_const_43 , _sage_const_47 ]
hecke_data = []
for p in primes_to_compute:
    try:
        T_p = BM.hecke_matrix(p)
        matrix_list = [[int(T_p[i, j]) for j in range(dim_BM)]
                       for i in range(dim_BM)]
        # Hecke eigenvalues (real, since Hecke matrices on Brandt
        # modules are symmetric / can be made so via Petersson)
        eigvals = T_p.eigenvalues()
        kind_K = prime_structure_K.get(p, {}).get("kind", "unknown")
        hecke_data.append({
            "prime": int(p),
            "kind_in_Q_sqrt_5": kind_K,
            "matrix": matrix_list,
            "trace": int(T_p.trace()),
            "det": int(T_p.det()),
            "eigvals_string": str(eigvals)[:_sage_const_200 ],
        })
        print(f"T_{p}: trace = {T_p.trace()}, det = {T_p.det()}, "
              f"K-kind = {kind_K}")
    except Exception as e:
        print(f"T_{p}: error {repr(e)[:100]}")

# Helper to recursively convert SAGE Integers to Python ints
def to_py(obj):
    if isinstance(obj, dict):
        return {to_py(k): to_py(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [to_py(x) for x in obj]
    try:
        return int(obj)
    except (TypeError, ValueError):
        try:
            return float(obj)
        except (TypeError, ValueError):
            return str(obj)

output = to_py({
    "field": "Q(sqrt 5)",
    "field_generator": "phi",
    "field_minimal_polynomial": "x^2 - x - 1",
    "field_class_number": K.class_number(),
    "prime_structure_K": prime_structure_K,
    "brandt_module_proxy": {
        "level": _sage_const_31 ,
        "weight": _sage_const_2 ,
        "dimension": dim_BM,
        "comment": "BrandtModule(31, 1) over Q -- proxy for icosian "
                   "Hecke action; SAGE 9.0 does not implement "
                   "BrandtModule over Q(sqrt 5)",
    },
    "hecke_operators": hecke_data,
    "sage_version": "9.0",
})

# Save
out_path = Path("data/brandt_level31.json")
out_path.parent.mkdir(parents=True, exist_ok=True)
with open(out_path, "w") as f:
    json.dump(output, f, indent=_sage_const_2 )

print()
print(f"Saved Brandt data with {len(hecke_data)} Hecke matrices to "
      f"{out_path}")
print(f"Brandt module dimension: {dim_BM}")

