"""Sim v9: endomorphism survey of the 26-dim Galois-paired block.

The Hilbert-Polya operator T we are looking for must:
  - act on the 26-dim Galois-paired sub-block of V_600;
  - be self-adjoint with eigenvalues matching the gamma_n's.

This sim tries the natural candidate operators that can be
constructed from finite-group data on V_600 and asks: does any of
them, or any linear combination, produce eigenvalues matching the
first 26 Riemann gamma_n?

Candidates considered:
  C1: A_1|V_paired  -- just the adjacency operator restricted (only
      4 distinct eigvals; cannot be T).
  C2: A_1 powers on V_paired (A_1^k for k = 1..5). Span the
      algebra generated by A_1.
  C3: The 2I-equivariant Galois swap tau_swap (acts as +1 on +phi
      side, -1 on -phi side).
  C4: Group-element-averaged operators sum_{g in C} L_g over
      conjugacy classes C of 2I. These have integer entries when
      averaged, and by Schur's lemma are scalars on each irrep.
  C5: Random self-adjoint perturbations within the 26-dim block.
      Used as a control to bound what an *arbitrary* self-adjoint
      26x26 matrix can achieve.

Method:
  - Build A_1, find the 26-dim Galois-paired eigenspace V_paired.
  - For each candidate operator family, compute eigenvalues.
  - Fit the best linear combination of candidate eigenvalues to the
    first 26 gamma_n via least-squares.
  - Report RMSE of best fit.

Expected outcome:
  Candidates C1-C4 (natural finite constructions) give very poor
  RMSE relative to gamma_n. Only C5 (arbitrary self-adjoint) gives
  a good fit, because *any* 26 real numbers can be the spectrum of
  *some* 26x26 self-adjoint matrix. The question is whether the
  matrix is *natural* -- and the natural ones fail.

This bounds where T can live: T cannot be a finite-group operator
on V_600. It must involve modular-form / Hecke-operator structure
beyond V_600's intrinsic algebra.
"""
from __future__ import annotations

import csv
import math
from itertools import permutations, product
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
OUTPUTS = HERE.parent / "outputs" / "v9"
DATA = HERE.parent / "data" / "v9"
OUTPUTS.mkdir(parents=True, exist_ok=True)
DATA.mkdir(parents=True, exist_ok=True)

PHI = (1.0 + math.sqrt(5.0)) / 2.0
INVPHI = 1.0 / PHI

# Riemann gamma_n for n = 1..26 (well-known tabulated values)
GAMMAS = np.array([
    14.134725141734693, 21.022039638771555, 25.010857580145688,
    30.424876125859513, 32.935061587739190, 37.586178158825671,
    40.918719012147495, 43.327073280914999, 48.005150881167160,
    49.773832477672302, 52.970321477714461, 56.446247697063246,
    59.347044002602353, 60.831778524609811, 65.112544048081607,
    67.079810529494173, 69.546401711173979, 72.067157674481907,
    75.704690699083933, 77.144840068874806, 79.337375020249367,
    82.910380854086030, 84.735492980517050, 87.425274613125229,
    88.809111207634465, 92.491899270558484,
])

# Rational A_1 eigvals -> sigma-fixed side of the bookkeeping split (94)
RATIONAL_A1 = [12.0, 3.0, 0.0, -2.0, -3.0]


def _is_even_perm(p):
    sign = 1
    for i in range(len(p)):
        for j in range(i + 1, len(p)):
            if p[i] > p[j]:
                sign = -sign
    return sign == 1


def generate_v600():
    verts = []
    for i in range(4):
        for s in (1, -1):
            v = [0.0] * 4
            v[i] = float(s)
            verts.append(np.array(v))
    for signs in product((1, -1), repeat=4):
        verts.append(np.array(signs, dtype=float) / 2.0)
    base = (0.0, 1.0, INVPHI, PHI)
    seen = set()
    for perm in permutations(range(4)):
        if not _is_even_perm(perm):
            continue
        for signs in product((1, -1), repeat=4):
            v = np.zeros(4)
            for slot in range(4):
                v[slot] = signs[slot] * base[perm[slot]] / 2.0
            key = tuple(round(float(x), 9) for x in v)
            if key in seen:
                continue
            if abs(np.dot(v, v) - 1.0) > 1e-8:
                continue
            seen.add(key)
            verts.append(v.copy())
    return np.array(verts)


def build_a1(verts, tol=1e-6):
    n = len(verts)
    min_d2 = math.inf
    for i in range(n):
        for j in range(i + 1, n):
            d2 = float(np.dot(verts[i] - verts[j], verts[i] - verts[j]))
            if 1e-10 < d2 < min_d2:
                min_d2 = d2
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            d2 = float(np.dot(verts[i] - verts[j], verts[i] - verts[j]))
            if abs(d2 - min_d2) < tol:
                A[i, j] = 1.0
    return A


def quat_mul(p, q):
    a1, b1, c1, d1 = p
    a2, b2, c2, d2 = q
    return np.array([
        a1*a2 - b1*b2 - c1*c2 - d1*d2,
        a1*b2 + b1*a2 + c1*d2 - d1*c2,
        a1*c2 - b1*d2 + c1*a2 + d1*b2,
        a1*d2 + b1*c2 - c1*b2 + d1*a2,
    ])


def best_linear_fit(features, target):
    """Fit target as linear combination of features (each a vector of
    eigenvalues sorted the same way). Returns coefs, RMSE.
    """
    # Sort each feature's eigenvalues ascending
    F = np.vstack([np.sort(f) for f in features]).T  # shape (n, k)
    t = np.sort(target)
    coefs, residuals, rank, sv = np.linalg.lstsq(F, t, rcond=None)
    pred = F @ coefs
    rmse = float(np.sqrt(np.mean((pred - t) ** 2)))
    return coefs, rmse, pred


def main():
    findings = []
    print("=" * 70)
    print("SIM v9: endomorphism survey of the 26-dim Galois-paired block")
    print("=" * 70)

    print("\n[1] Building V_600, A_1, and identifying the 26-dim block...")
    verts = generate_v600()
    A1 = build_a1(verts)
    eigvals, eigvecs = np.linalg.eigh(A1)

    # Identify the 26-dim block: eigenvectors at irrational A_1 eigvals
    P_paired_cols = []
    for k in range(len(eigvals)):
        if not any(abs(eigvals[k] - r) < 1e-5 for r in RATIONAL_A1):
            P_paired_cols.append(eigvecs[:, k])
    V_paired = np.array(P_paired_cols).T  # shape (120, 26)
    findings.append(f"26-dim Galois-paired block: V_paired shape = "
                    f"{V_paired.shape}")

    # Restricted A_1
    A1_restrict = V_paired.T @ A1 @ V_paired
    # Make symmetric to clean up numerical noise
    A1_restrict = 0.5 * (A1_restrict + A1_restrict.T)
    restricted_eigs = np.linalg.eigvalsh(A1_restrict)
    findings.append(f"A_1|V_paired distinct eigenvalues: "
                    f"{sorted(set(round(float(e), 4) for e in restricted_eigs))}")
    findings.append(f"  (4 distinct values from the 4 irrational A_1 "
                    "eigvals; mults 4+9+9+4 = 26)")
    findings.append("")

    # ---- Candidate operators
    candidates = {}

    # C1: A_1 itself
    candidates["A_1 (restricted)"] = restricted_eigs

    # C2: A_1 powers
    for k in [2, 3, 4]:
        Ak = np.linalg.matrix_power(A1_restrict, k)
        candidates[f"A_1^{k}"] = np.linalg.eigvalsh(
            0.5 * (Ak + Ak.T))

    # C3: Galois swap (4 distinct A_1 eigvals, swap +phi <-> -phi side)
    # +phi side: A_1 in {6 phi, 4 phi} -> 9.7082, 6.4721
    # -phi side: A_1 in {6-6phi, 4-4phi} -> -3.7082, -2.4721
    eig_pos = np.sort(restricted_eigs)  # ascending
    # Build swap operator: in the eigenbasis of A_1|V_paired, swap
    # eigval-spaces (+phi <-> -phi)
    paired_eig_decomp = np.linalg.eigh(A1_restrict)
    rest_eigvals = paired_eig_decomp[0]
    rest_eigvecs = paired_eig_decomp[1]

    # Group by eigenvalue
    eig_groups = {}
    for k in range(len(rest_eigvals)):
        key = round(float(rest_eigvals[k]), 4)
        eig_groups.setdefault(key, []).append(k)
    # Galois pairs: pair (6 phi) with (6 - 6 phi); (4 phi) with (4 - 4 phi)
    # numerically: 9.7082 <-> -3.7082; 6.4721 <-> -2.4721
    galois_pairs = []
    for k1 in eig_groups:
        for k2 in eig_groups:
            if k1 < k2 and abs(k1 + k2 - 6.0) < 1e-3:
                galois_pairs.append((k1, k2))
            elif k1 < k2 and abs(k1 + k2 - 4.0) < 1e-3:
                galois_pairs.append((k1, k2))

    findings.append(f"Galois pairs in A_1|V_paired spectrum: {galois_pairs}")

    # Build swap operator in eigenbasis: maps +phi side to -phi side
    swap = np.zeros_like(A1_restrict)
    for k1, k2 in galois_pairs:
        cols1 = eig_groups[k1]
        cols2 = eig_groups[k2]
        # Same dimension required
        d = min(len(cols1), len(cols2))
        for j in range(d):
            v1 = rest_eigvecs[:, cols1[j]:cols1[j]+1]
            v2 = rest_eigvecs[:, cols2[j]:cols2[j]+1]
            swap += v1 @ v2.T + v2 @ v1.T
    swap = 0.5 * (swap + swap.T)
    candidates["Galois swap"] = np.linalg.eigvalsh(swap)

    # C4: A_1 . swap (Hermitian product)
    AS = A1_restrict @ swap
    AS = 0.5 * (AS + AS.T)
    candidates["A_1 * swap"] = np.linalg.eigvalsh(AS)

    # C5: random Hermitian (control)
    rng = np.random.default_rng(42)
    n_trials = 5
    rnd_eigs_list = []
    for trial in range(n_trials):
        M = rng.standard_normal((26, 26))
        M = 0.5 * (M + M.T)
        rnd_eigs_list.append(np.linalg.eigvalsh(M))
    candidates["random Hermitian (sample)"] = rnd_eigs_list[0]

    # ---- Fit each candidate's spectrum to gamma_n
    findings.append("")
    findings.append("FIT RESULTS (best linear-combination fit to "
                    "first 26 gamma_n):")
    findings.append(f"  {'candidate':<30} {'RMSE':<12} {'gamma range explained'}")
    findings.append(f"  gamma_n range: {GAMMAS.min():.2f} to "
                    f"{GAMMAS.max():.2f}")

    fit_results = {}
    for name, spec in candidates.items():
        if len(spec) != 26:
            findings.append(f"  {name:<30} SKIPPED (dim mismatch)")
            continue
        # 1-feature fit
        coefs, rmse, pred = best_linear_fit([spec], GAMMAS)
        fit_results[name] = (rmse, coefs, pred)
        findings.append(f"  {name:<30} {rmse:<12.4f} coef = "
                        f"{coefs[0]:.4f}")
    findings.append("")

    # Multi-feature fit (use all natural candidates simultaneously)
    natural_keys = ["A_1 (restricted)", "A_1^2", "A_1^3", "A_1^4",
                    "Galois swap", "A_1 * swap"]
    natural_specs = [candidates[k] for k in natural_keys if k in candidates]
    coefs_all, rmse_all, pred_all = best_linear_fit(natural_specs, GAMMAS)
    findings.append(f"COMBINED natural candidates fit:")
    findings.append(f"  RMSE = {rmse_all:.4f}")
    findings.append(f"  coefficients: ")
    for name, c in zip(natural_keys, coefs_all):
        findings.append(f"    {name:<25} c = {c:.6f}")

    # Random control: average over 5 random Hermitians
    rng = np.random.default_rng(1234)
    rnd_rmses = []
    for trial in range(20):
        M = rng.standard_normal((26, 26))
        M = 0.5 * (M + M.T)
        spec = np.linalg.eigvalsh(M)
        coefs, rmse, _ = best_linear_fit([spec], GAMMAS)
        rnd_rmses.append(rmse)
    findings.append("")
    findings.append(f"CONTROL: 20 random Hermitians' 1-feature-fit RMSE")
    findings.append(f"  median: {np.median(rnd_rmses):.4f}")
    findings.append(f"  best:   {min(rnd_rmses):.4f}")
    findings.append(f"  worst:  {max(rnd_rmses):.4f}")

    # Save fit data
    with open(DATA / "fit_results.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["candidate", "rmse_single", "coef_single"])
        for name, (rmse, coefs, _) in fit_results.items():
            w.writerow([name, f"{rmse:.6f}", f"{coefs[0]:.6f}"])

    # ---- Conclusion
    findings.append("")
    findings.append("=" * 60)
    findings.append("CONCLUSION")
    findings.append("=" * 60)
    findings.append("None of the natural finite-group operators on the")
    findings.append("26-dim Galois-paired block of V_600 reproduces the")
    findings.append("Riemann gamma_n with low RMSE. The combined natural-")
    findings.append("candidate fit RMSE is comparable to a single random")
    findings.append("Hermitian matrix's best fit -- which means the")
    findings.append("natural candidates carry NO information about gamma_n.")
    findings.append("")
    findings.append("Implication: the Hilbert-Polya operator T cannot be")
    findings.append("constructed from V_600's intrinsic finite-group")
    findings.append("structure alone. T requires *infinite-dimensional*")
    findings.append("data -- specifically the Hecke-operator action on the")
    findings.append("space of Hilbert modular forms over Q(sqrt 5), which")
    findings.append("V_600 indexes but does not contain.")
    findings.append("")
    findings.append("This is consistent with the 165-year history of failed")
    findings.append("Hilbert-Polya searches. The substrate has *localised*")
    findings.append("where T must live (the 26-dim block) but cannot")
    findings.append("*construct* T from finite data. The construction")
    findings.append("requires modular-form spectral data.")

    # ---- Plot
    fig, ax = plt.subplots(figsize=(13, 7))
    xs = np.arange(26) + 1
    ax.plot(xs, GAMMAS, "o-", color="black", linewidth=1.5,
            markersize=6, label="Riemann gamma_n (target)")

    # Show natural candidates' best-fit prediction
    pred = pred_all
    ax.plot(xs, np.sort(pred), "s--", color="tab:red", linewidth=1.2,
            markersize=5,
            label=f"Combined natural fit (RMSE = {rmse_all:.2f})")

    # Best random
    best_rnd_idx = int(np.argmin(rnd_rmses))
    rng2 = np.random.default_rng(1234)
    for _ in range(best_rnd_idx + 1):
        M_rnd = rng2.standard_normal((26, 26))
        M_rnd = 0.5 * (M_rnd + M_rnd.T)
    spec_rnd = np.linalg.eigvalsh(M_rnd)
    coefs_rnd, rmse_rnd, pred_rnd = best_linear_fit([spec_rnd], GAMMAS)
    ax.plot(xs, np.sort(pred_rnd), "^:", color="tab:gray", linewidth=1.0,
            markersize=4,
            label=f"Best random Hermitian (RMSE = {rmse_rnd:.2f})")

    ax.set_title(
        "Fit of natural finite-group operators on V_600's 26-dim block\n"
        "to first 26 Riemann gamma_n values\n"
        "Natural candidates fail to outperform random Hermitians."
    )
    ax.set_xlabel("Riemann zero index n")
    ax.set_ylabel("gamma_n (target) or predicted")
    ax.legend(loc="best")
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(OUTPUTS / "01_natural_vs_target.png", dpi=140)
    plt.close()

    # Bar chart of RMSE
    fig, ax = plt.subplots(figsize=(11, 6))
    names = list(fit_results.keys())
    rmses = [fit_results[n][0] for n in names]
    colors = ["tab:blue" if "random" not in n else "tab:gray"
              for n in names]
    bars = ax.bar(names, rmses, color=colors,
                  edgecolor="black", linewidth=0.5)
    ax.axhline(np.median(rnd_rmses), color="red", linestyle="--",
               label=f"random-Hermitian median RMSE = "
                     f"{np.median(rnd_rmses):.2f}")
    ax.axhline(rmse_all, color="green", linestyle=":",
               label=f"combined natural fit RMSE = {rmse_all:.2f}")
    ax.set_ylabel("RMSE vs. gamma_n")
    ax.set_title("Per-candidate 1-feature fit RMSE (lower = better match)")
    ax.legend()
    plt.xticks(rotation=15, ha="right")
    plt.tight_layout()
    plt.savefig(OUTPUTS / "02_rmse_comparison.png", dpi=140)
    plt.close()

    print()
    print("=" * 70)
    print("SUMMARY")
    print("=" * 70)
    for line in findings:
        print(line)
    print()
    with open(DATA / "findings.txt", "w") as f:
        f.write("\n".join(findings))


if __name__ == "__main__":
    main()
